# Generated by Django 2.1.7 on 2020-01-14 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodstype',
            name='image',
        ),
        migrations.AddField(
            model_name='goodstype',
            name='image_url',
            field=models.URLField(default='', verbose_name='商品类型图片'),
        ),
    ]
